[project]
name = "ad-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "altair>=5.4.1",
    "numpy>=2.1.2",
    "pandas>=2.2.3",
    "streamlit>=1.39.0",
]
